version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: product-apis
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data


